spring:
  application:
    name: EventClean

  datasource:
    url: jdbc:postresql://localhost:5431/EventClean
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true

  flyway:
    enable: true